API_TOKEN = '5290929906:AAHghK9C4__xu5np-aAOQsNf7OXsUUNRArE'

DEBUG_ID = '<YOUR_DEBUG_ID>'

GET_DEBUG_INFO = False

LOGGING = True

MODE = 'NORMAL'

CONNECTION_TYPE = 'POLLING'

WEBHOOK_HOST = '<YOUR_WEBHOOK_HOST>'

WEBAPP_PORT = '<YOUR_WEBAPP_PORT>'